export SPARK_MASTER_HOST='0.0.0.0'
export SPARK_MASTER_PORT=7077
export SPARK_MASTER_WEBUI_PORT=8080
export SPARK_WORKER_WEBUI_PORT=8081
export SPARK_WORKER_MEMORY=8g
export SPARK_WORKER_CORES=8
export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
export HADOOP_HOME=/opt/hadoop
export SPARK_DIST_CLASSPATH=$(hadoop classpath)


SPARK_DIST_CLASSPATH="$HADOOP_HOME/client/*"
SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:$($HADOOP_HOME/bin/hadoop --config $HADOOP_CONF_DIR classpath)"
SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:/opt/hive/lib/*"
if [ -n "$HADOOP_EXTRA_CLASSPATH" ]; then
  SPARK_DIST_CLASSPATH="$SPARK_DIST_CLASSPATH:$HADOOP_EXTRA_CLASSPATH"
fi
export SPARK_DIST_CLASSPATH