version: "2"
services:

  hive-server:
    image: hadoop:3.3.5-r1
    volumes:
      - "./configs/hive/log4j.properties:/opt/hive/conf/log4j.properties"
      - "./test:/tmp/test"
    env_file:
      - ./hive.cfg
    command: ["hive", "--service", "hiveserver2"]
    environment:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/hive/bin:/opt/spark/bin'
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hive/conf"
    ports:
      - "10000:10000"
    networks:
      hadoop:

  hive-metastore:
    image: hadoop:3.3.5-r1
    env_file:
      - ./hive.cfg
    volumes:
      - "./configs/hive/log4j.properties:/opt/hive/conf/log4j.properties"
    command: ["hive", "--service", "metastore"]
    environment:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/hive/bin:/opt/spark/bin'
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hive/conf"
    ports:
      - "9083:9083"
    networks:
      hadoop:

  hive-metastore-init:
    image: hadoop:3.3.5-r1
    restart: no
    depends_on:
      - hive-metastore-postgresql
    env_file:
      - ./hive.cfg
    volumes:
      - "./configs/hive/log4j.properties:/opt/hive/conf/log4j.properties"
    command: ["/opt/hive/bin/schematool", "-dbType", "postgres", "-initSchema", "--verbose"]
    environment:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/hive/bin:/opt/spark/bin'
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hive/conf"
    networks:
      hadoop:

  hive-metastore-postgresql:
    image: docker-registry.services.linux2be.com:443/devops-f/devops/postgresql:15.4.0.c
    restart: always
    environment:
       POSTGRESQL_USERNAME: "postgres"
       POSTGRESQL_PASSWORD: "phahMMMddd999h7uutheePighMMMdsdsdss"
       POSTGRESQL_DATABASE: "hive-metastore"
       CONSUL_AGENT: "false"
    ports:
      - "35432:5432"
    volumes:
      - "./configs/postgres:/opt/bitnami/postgresql/conf/conf.d"
      - "postgres-15-2-bitnami_data:/bitnami/postgresql"
    networks:
      hadoop:
        aliases:
          - postgres

  namenode:
    image: hadoop:3.3.5-r1
    hostname: namenode
    volumes:
      - ./Makefile:/opt/hadoop/Makefile
    ports:
      - 9870:9870
    env_file:
      - ./hadoop.cfg
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HIVE_HOME: "/opt/hive"
    command: ["hdfs", "namenode"]
    networks:
      hadoop:

  datanode:
    image: hadoop:3.3.5-r1
    volumes:
      - hdfs_datanode:/data/hdfs
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./hadoop.cfg
    networks:
      hadoop:

  resourcemanager:
    image: hadoop:3.3.5-r1
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./hadoop.cfg
    networks:
      hadoop:

  nodemanager:
    image: hadoop:3.3.5-r1
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./hadoop.cfg
    networks:
      hadoop:

  spark-master:
    image: hadoop:3.3.5-r1
    volumes:
        - "./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf"
        - "./configs/spark/spark-env.sh:/opt/spark/conf/spark-env.sh"
    command: [ "spark-class", "org.apache.spark.deploy.master.Master" ]
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - ./hadoop.cfg
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/spark/bin"
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/spark/conf"
    networks:
      hadoop:

  spark-worker:
    image: hadoop:3.3.5-r1
    volumes:
        - "./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf"
        - "./configs/spark/spark-env.sh:/opt/spark/conf/spark-env.sh"
    command: [ "spark-class", "org.apache.spark.deploy.worker.Worker" , "spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop.cfg
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/spark/bin"
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/spark/conf"
    networks:
      hadoop:

  historyserver:
    image: hadoop:3.3.5-r1
    command: [ "yarn", "historyserver" ]
    volumes:
      - hdfs_historyserver:/data/hdfs/
    ports:
      - 8188:8188
    env_file:
      - ./hadoop.cfg
    environment:
      PATH: "/opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin"

    networks:
      hadoop:

volumes:
  postgres-15-2-bitnami_data:
  hdfs_datanode:
  hdfs_historyserver:
networks:
  hadoop: