version: "2"
services:

  hive-server:
    image: hadoop:3.3.5-ubuntu-r1
    restart: always
    volumes:
      - "./configs/hive/log4j.properties:/opt/hive/conf/log4j.properties"
      - "./configs/hive/hive-env.sh:/opt/hive/conf/hive-env.sh"
      - "./test:/tmp/test"
      - "./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf"
      - "./configs/spark/spark-env.sh:/opt/spark/conf/spark-env.sh"
      - spark_staging:/opt/hadoop/.sparkStaging
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    env_file:
      - ./hive.cfg
    command: ["hive", "--service", "hiveserver2"]
    #entrypoint: tail -f /dev/null
    environment:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/hive/bin:/opt/spark/bin'
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hive/conf"
    ports:
      - "10000:10000"
    networks:
      hadoop:
    depends_on:
      - hive-metastore



  hive-metastore:
    image: hadoop:3.3.5-ubuntu-r1
    restart: always
    env_file:
      - ./hive.cfg
    volumes:
      - "./configs/hive/log4j.properties:/opt/hive/conf/log4j.properties"
      - "./configs/hive/hive-env.sh:/opt/hive/conf/hive-env.sh"
      - "./test:/tmp/test"
      - "./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf"
      - "./configs/spark/spark-env.sh:/opt/spark/conf/spark-env.sh"
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    command: ["hive", "--service", "metastore"]
    environment:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/hive/bin:/opt/spark/bin'
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hive/conf"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    
    networks:
      hadoop:
        aliases:
          - odin-ha.omsk.linux2be.com

  hive-metastore-init:
    image: hadoop:3.3.5-ubuntu-r1
    restart: no
    volumes:
      - "./configs/hive/log4j.properties:/opt/hive/conf/log4j.properties"
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    depends_on:
      - hive-metastore-postgresql
    env_file:
      - ./hive.cfg
    command: ["/opt/hive/bin/schematool", "-dbType", "postgres", "-initSchema", "--verbose" ]
    environment:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/hive/bin:/opt/spark/bin'
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_CONF_DIR: "/opt/hive/conf"
    networks:
      hadoop:

  hive-metastore-postgresql:
    image: docker-registry.services.linux2be.com:443/devops-f/devops/postgresql:15.4.0.c
    restart: always
    volumes:
      - "./configs/postgres:/opt/bitnami/postgresql/conf/conf.d"
      - "postgres-15-2-bitnami_data:/bitnami/postgresql"
    environment:
       POSTGRESQL_USERNAME: "postgres"
       POSTGRESQL_PASSWORD: "phahMMMddd999h7uutheePighMMMdsdsdss"
       POSTGRESQL_DATABASE: "hive-metastore"
       CONSUL_AGENT: "false"
    ports:
      - "35432:5432"
    networks:
      hadoop:
        aliases:
          - postgres

  namenode:
    image: hadoop:3.3.5-ubuntu-r1
    restart: always
    hostname: namenode
    volumes:
      - ./Makefile:/opt/hadoop/Makefile
      - hdfs_datanode:/data/hdfs
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    ports:
      - 9870:9870
    env_file:
      - ./hadoop.cfg
    environment:
      ENSURE_NAMENODE_DIR: "/data/hdfs/namenode"
      # ENSURE_NAMENODE_CLUSTERID
      HIVE_HOME: "/opt/hive"
    command: ["hdfs", "namenode"]
    networks:
      hadoop:

  datanode:
    image: hadoop:3.3.5-ubuntu-r1
    restart: no
    hostname: datanode
    volumes:
      - hdfs_datanode:/data/hdfs
      - spark_staging:/opt/hadoop/.sparkStaging
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./hadoop.cfg
    networks:
      hadoop:

  resourcemanager:
    image: hadoop:3.3.5-ubuntu-r1
    restart: no
    hostname: resourcemanager
    volumes:
      - spark_staging:/opt/hadoop/.sparkStaging
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./hadoop.cfg
    networks:
      hadoop:

  nodemanager:
    image: hadoop:3.3.5-ubuntu-r1
    restart: no
    hostname: nodemanager
    volumes:
      - spark_staging:/opt/hadoop/.sparkStaging
      - "./configs/keytabs:/opt/keytabs"
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./hadoop.cfg
    networks:
      hadoop:

  spark-master:
    image: hadoop:3.3.5-ubuntu-r1
    restart: always
    hostname: spark-master
    volumes:
      - "./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf"
      - "./configs/spark/spark-env.sh:/opt/spark/conf/spark-env.sh"
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    command: [ "spark-class", "org.apache.spark.deploy.master.Master" ]
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - ./hadoop.cfg
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/spark/bin"
      HADOOP_HOME: "/opt/hadoop"
    networks:
      hadoop:

  spark-worker:
    image: hadoop:3.3.5-ubuntu-r1
    restart: always
    hostname: spark-worker
    volumes:
      - "./configs/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf"
      - "./configs/spark/spark-env.sh:/opt/spark/conf/spark-env.sh"
      - "./configs/keytabs:/opt/keytabs"
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
    command: [ "spark-class", "org.apache.spark.deploy.worker.Worker" , "spark://spark-master:7077"]
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop.cfg
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin:/opt/spark/bin"
      HADOOP_HOME: "/opt/hadoop"
    networks:
      hadoop:

  historyserver:
    image: hadoop:3.3.5-ubuntu-r1
    restart: always
    command: [ "yarn", "historyserver" ]
    entrypoint: tail -f /dev/null
    volumes:
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
      - hdfs_historyserver:/data/hdfs/
      - "./configs/keytabs:/opt/keytabs"
    ports:
      - 8188:8188
    env_file:
      - ./hadoop.cfg
    environment:
      PATH: "/opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hadoop/bin"
    networks:
      hadoop:

  openldap:
    image: devsadds/openldap:1.5.0
    restart: always
    container_name: openldap
    hostname: "omsk.linux2be.com"
    volumes:
      - "./configs/keytabs:/opt/keytabs"
      - "openldap_ldap_data:/var/lib/ldap"
      - "openldap_ldap_slap:/etc/ldap/slapd.d"
      - "openldap_ldap_certs:/container/service/slapd/assets/certs"
      - "./configs/openldap/schemas:/openldap/schemas"
    environment:
      LDAP_ORGANISATION: "Linux2be"
      LDAP_DOMAIN: "omsk.linux2be.com"
      LDAP_ADMIN_PASSWORD: "admin_password"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonlyuser"
      LDAP_READONLY_USER_PASSWORD: "readonlypassword"
      LDAP_BACKEND: "mdb"
      KEEP_EXISTING_CONFIG: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      LDAP_TLS: "false"
      LDAP_TLS_ENFORCE: "false"
      stdin_open: true
      tty: true
    networks:
      hadoop:
        aliases:
          - omsk.linux2be.com

  krb5:
    image: krb5:1.0.0-ubuntu-r2
    volumes:
      - "./configs/krb/krb5.conf:/etc/krb5.conf"
      - "./configs/krb/kdc.conf:/etc/kerberos/krb5kdc/kdc.conf"
      - "./configs/krb/kadm5.acl:/etc/kerberos/krb5kdc/kadm5.acl"
      - "./configs/keytabs:/opt/keytabs"
      - "./logs/krb5:/var/log"
      - "krb5kdc_database_1:/var/lib/krb5kdc"
      - "./configs/krb/openldappassword.keyfile:/etc/krb5kdc/openldappassword.keyfile"
    environment:
      KERBEROS_REALM: "OMSK.LINUX2BE.COM"
      LDAP_ADMIN_PASSWORD: "admin_password"
      LDAP_SEARCH_BASE: "dc=omsk,dc=linux2be,dc=com"
      KRB5_KDC_PROFILE: "/etc/kerberos/krb5kdc/kdc.conf"
      KRB5_KDC_PASSWORD: "krb5"
    domainname: omsk.linux2be.com
    #command: ["krb5kdc", "-d", "/var/lib/krb5kdc/database", "-n" ]
    command: ["krb5kdc", "-n" ]
    #entrypoint: tail -f /dev/null
    restart: always
    ports:
      - "88:88"
      - "749:749"
    depends_on:
      - openldap
    networks:
      hadoop:
        aliases:
          - kerberos.omsk.linux2be.com
          - omsk.linux2be.com


volumes:
  postgres-15-2-bitnami_data:
  hdfs_datanode:
  hdfs_historyserver:
  spark_staging:
  openldap_ldap_data:
  openldap_ldap_slap:
  openldap_ldap_certs:
  krb5kdc_database_1:

networks:
  hadoop: